# Generated by Django 6.0.3 on 2026-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bias_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
