# Generated by Django 6.0.3 on 2026-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0002_answer_bias_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
