# Generated by Django 6.0.3 on 2026-04-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0003_annotator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='app_projeto.batch'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_projeto.label'),
        ),
    ]
