# Generated by Django 6.0.3 on 2026-04-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0004_annotation_batch_alter_annotation_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='bias_type',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_num',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
