# Generated by Django 6.0.3 on 2026-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0005_remove_answer_bias_type_remove_batch_batch_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='label',
        ),
        migrations.AddField(
            model_name='annotation',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='annotations', to='app_projeto.label'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
