# Generated by Django 6.0.3 on 2026-05-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0006_remove_annotation_label_annotation_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
